FROM golang:1.13-alpine

ENV GOBIN /go/bin
RUN apk add  --no-cache git

RUN  mkdir -p /app

WORKDIR /app

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon  -log-prefix=false --build="go build -mod=vendor -o ingestion ." --command=./ingestion